In [50]:
import numpy as np
A = np.arange(12).reshape((4,3))
print(A)
B = A.sum(axis=0)
print(B)
print(np.add(A.T, B[:,np.newaxis]).T)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[18 22 26]
[[18 23 28]
 [21 26 31]
 [24 29 34]
 [27 32 37]]
